---
title: "Protests and Internet"
author: "Alexander Mohn"
date: "May 14, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(stringr)
library(readr)
library(tidyr)
library(caret)
library(pls)
library(ncvreg)
library(factoextra)
```

### Protest Data Cleaning
```{r, warning = FALSE}
protests <- read.csv("./Data/Protests.tab", sep = "\t", encoding = "UTF-8")
capitals <- read.csv("./Data/CountryCapitals.csv", sep = "\t", encoding = "UTF-8")
capitals <- capitals %>% mutate(country = trimws(as.character(country), which = "right"),
                                capital = trimws(as.character(capital), which = "right")) %>%
  mutate(capital = str_replace_all(capital, "-", " "))
protests <- protests %>% left_join(capitals, by = c("country")) %>%
  # Selects, case-insensitively, protests where the location is either national or
  # is the national capital
  filter(str_detect(location, paste("(?i)(\\bnational\\b)|(", capital, ")", sep = ""))) %>%
  # Discard unneeded columns
  select(country, region, year, protesterviolence, 
         location, participants, protesteridentity, 19:29) %>%
  # Extract number of participants
  mutate(size = parse_number(as.character(participants)))
# Fix text-based numbers
non_numeric <- protests %>% filter(is.na(size)) %>%
  mutate(size = case_when(str_detect(participants, "(?i)^dozens") ~ 10,
                          str_detect(participants, "(?i)^thousands") ~ 1000,
                          str_detect(participants, "(?i)^tens of thousands") ~ 10000,
                          str_detect(participants, "(?i)^hundreds of thousands") ~ 100000,
                          str_detect(participants, "(?i)^hundreds") ~ 100,
                          str_detect(participants, "(?i)^(several)|(a few) hundred") ~ 100,
                          str_detect(participants, "(?i)^(several)|(a few) thousand") ~ 1000,
                          str_detect(participants, "(?i)million") ~ 1000000,
                          str_detect(participants, "(?i)^few dozen") ~ 10))
# Merge it back in and calculate order of magnitude
protests <- protests %>% filter(!is.na(size)) %>%  bind_rows(non_numeric) %>%
  mutate(size = 10^(floor(log10(size)))) %>% mutate(size = as.numeric(size))
rm(non_numeric)
```

### Load Population Data
```{r}
# Get population information
populations <- read.csv("./Data/Population/Countries.csv", skip = 4)
populations <- populations %>% select(Country.Name, 35:62) %>%
  gather("Year", "Population", 2:29) %>% mutate(Year = parse_number(Year)) %>%
  mutate(Country.Name = as.character(Country.Name))
populations[populations$Country.Name == "Iran, Islamic Rep.", "Country.Name"] <- "Iran"
populations[populations$Country.Name == "Egypt, Arab Rep.", "Country.Name"] <- "Egypt"
```

### Load Internet Data
```{r}
# Get internet use info
internet <- read.csv("./Data/Internet/Users.csv", skip = 4)
internet <- internet %>% select(Country.Name, 35:62) %>%
  gather("Year", "InternetUsers", 2:29) %>% mutate(Year = parse_number(Year)) %>%
  mutate(Country.Name = as.character(Country.Name))
internet[internet$Country.Name == "Iran, Islamic Rep.", "Country.Name"] <- "Iran"
internet[internet$Country.Name == "Egypt, Arab Rep.", "Country.Name"] <- "Egypt"
```

### VDem Data
```{r}
# ## Loading from original dataset (commented out because BIG)
# vdem <- read.csv("./Data/Country_Year_V-Dem_Full+others_CSV_v9/V-Dem_post_1990.csv")
# vdem <- vdem %>% select(country_name, year, v2mecenefm, v2mecenefi, v2mecrit, v2merange, 
#                         v2meharjrn, v2mecorrpt, v2psbars, v2clacfree, v2clkill, v2clstown,
#                         v2clsocgrp, v2pepwrses) %>%
#   rename(censorship = v2mecenefm, internetCensorship = v2mecenefi, critical = v2mecrit, 
#          mediaRange = v2merange, harrassJournalists = v2meharjrn, corrupt = v2mecorrpt,
#          partyBarriers = v2psbars, academicCulturalExpression = v2clacfree, 
#          politicalMurder = v2clkill, stateEconomyControl = v2clstown, socialEquality = v2clsocgrp,
#          socioEconomicPower = v2pepwrses)
# write.csv(vdem, "./Data/VDemSubset.csv", row.names = FALSE)
vdem <- read.csv("./Data/VDemSubset.csv")
```

### Join Data
```{r, warning = FALSE}
regions <- protests %>% select(country, region) %>% distinct()
byYear <- protests %>% group_by(country, year) %>% summarize(sumProtestors = sum(size),
                                                             meanProtestors = mean(size),
                                                             medianProtestors = median(size),
                                                             numberProtests = n()) %>%
  left_join(populations, by = c("country" = "Country.Name",
                                "year" = "Year")) %>%
  mutate(popPctSum = (sumProtestors / Population) * 100,
         popPctMean = (meanProtestors / Population) * 100,
         popPctMedian = (medianProtestors / Population) * 100) %>%
  left_join(internet, by = c("country" = "Country.Name",
                             "year" = "Year")) %>%
  left_join(vdem, by = c("country" = "country_name",
                         "year" = "year")) %>%
  left_join(regions, by = c("country" = "country"))
countryList <- byYear %>% select(country) %>% distinct()
regionList <- byYear %>% ungroup() %>% select(region) %>% distinct() %>% arrange(region) %>%
  mutate(names = c("South America", "Central America", "Carribean/North America",
                   "Europe", "Asia", "Middle East/North Africa", "Sub-Saharan Africa",
                   "Oceania"))
```

### Modeling
```{r, warning = FALSE}
# Select variables of interest
noNulls <- na.omit(byYear)
noNulls <- noNulls %>% select(country, year, popPctMean, Population, 
                              InternetUsers, censorship, internetCensorship,
                              critical, mediaRange, harrassJournalists, corrupt, partyBarriers, 
                              academicCulturalExpression, politicalMurder,
                              stateEconomyControl, socialEquality, socioEconomicPower)

# Model using partial least squares
set.seed(15)
fit.control <- trainControl(method = "repeatedcv", number = 5, repeats = 10)
model <- formula(popPctMean ~ InternetUsers + censorship + internetCensorship +
                   critical + mediaRange + harrassJournalists + corrupt + partyBarriers +
                   academicCulturalExpression + politicalMurder + stateEconomyControl +
                   socialEquality + socioEconomicPower)
pls.fit <- train(model, data = noNulls, method = "pls", 
                 trControl = fit.control, tuneGrid = data.frame(ncomp = 1:13))
pls.fit$finalModel$loadings
varImp(pls.fit)

# Model with LASSO
set.seed(15)
lasso.fit <- cv.ncvreg(X = noNulls[,-1:-3], y = noNulls$popPctMean, penalty = "lasso")
coeffs <- lasso.fit$fit$beta[,lasso.fit$fit$lambda == lasso.fit$lambda.min]
coeffs <- coeffs[coeffs!=0]
summary(lasso.fit)
coeffs
```

### Clustering
```{r, warning = FALSE}
clust <- noNulls %>% ungroup() %>% select(-country, -year)
row.names(clust) <- paste(noNulls$country, noNulls$year, sep = "_")
dist <- daisy(scale(clust), metric = "gower")
pmClusts <- pam(dist, scale(clust), k = 3) # Number of clusters from gap method
pm$medoids
pm$clusinfo
print("Cluster 1:")
colMeans(clust[pm$clustering == 1,])
print("Cluster 2:")
colMeans(clust[pm$clustering == 2,])
print("Cluster 3:")
colMeans(clust[pm$clustering == 3,])
clust$cluster <- pm$clustering
names <- row.names(clust)
clust$country <- unlist(str_split(names, "_"))[1]
clust$year <- unlist(str_split(names, "_"))[2]
```

### Modeling with clusters
```{r, warning = FALSE}
set.seed(15)
model <- formula(popPctMean ~ InternetUsers + censorship + internetCensorship +
                   critical + mediaRange + harrassJournalists + corrupt + partyBarriers +
                   academicCulturalExpression + politicalMurder + stateEconomyControl +
                   socialEquality + socioEconomicPower + cluster)
pls.fit.clust <- train(model, data = clust, method = "pls", trControl = fit.control, 
                       tuneGrid = data.frame(ncomp = 1:14))
pls.fit.clust$finalModel$loadings
varImp(pls.fit.clust)

set.seed(15)
lasso.fit.clust <- cv.ncvreg(X = clust[,c(-1,-17:-18)], y = clust$popPctMean, penalty = "lasso")
coeffs.clust <- lasso.fit.clust$fit$beta[,lasso.fit.clust$fit$lambda == lasso.fit.clust$lambda.min]
coeffs.clust <- coeffs.clust[coeffs.clust != 0]
summary(lasso.fit.clust)
coeffs.clust
```